### ISSUE TITLE
Reseteo de contraseña para el supervisor

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#108]
**La mejora está relacionada a un problema? Por favor describe.**
Se requiere habilitar el api de reseteo de contraseña para el supervisor, ya que actualmente solo lo puede hace el administrador del sistema. 'api/v1/admin/user/passwordreset'

**Describa la solución que propones**
Una descripción clara y concisa de lo que quieres que pase.

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
API: /api/v1/supervisor/user/passwordreset listo
