### ISSUE TITLE
Cambiar el usuario por parte del supervisor

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#109]
**La mejora está relacionada a un problema? Por favor describe.**
Se requiere habilitar el api para que el supervisor pueda actualizar si así lo requiere el correo electronico del usuario que lo solicite por cuestiones ajenas a la plataforma. "api/v1/admin/user/changeuser"

**Describa la solución que propones**
Una descripción clara y concisa de lo que quieres que pase.

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by iHectorLeon** [comment]
manda un error 404 de que no encuentra el api.
<img width="442" alt="captura de pantalla 2018-12-17 a la s 18 14 29" src="https://user-images.githubusercontent.com/20383899/50123772-ab27c080-0227-11e9-9791-7f04b7af311c.png">
<img width="553" alt="captura de pantalla 2018-12-17 a la s 18 14 15" src="https://user-images.githubusercontent.com/20383899/50123773-abc05700-0227-11e9-86b8-38200153d56f.png">

**Comment by aclarturocastro** [comment]
Reparado

v1.5.13 ee6ff4b
