### ISSUE TITLE
Agregar la opcion de guardar los datos del grupo en el api de Solicitudes

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#110]
**La mejora está relacionada a un problema? Por favor describe.**
Se requiere agregar informacion de grupos y usuarios a una solicitud de alta por parte del supervisor, para que pueda retomar esta solicitud en determinados momento con los datos de los grupos y los alumnos que se generaron en cada creación de grupo

**Describa la solución que propones**
Una descripción clara y concisa de lo que quieres que pase.

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
Se agregan 3 propiedades: 

```
temp1 = [];
temp2 = [];
temp3 = [];
```

Con el API finish las 3 propiedades se resetean ([])

v1.5.10 83aabd5
