### ISSUE TITLE
Homologación de mensaje

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#112]
**Describe la falla**
Homologar el mensaje que regresa el api "api/v1/supervisor/user/getgroups?username=", en los casos de que el usuario esta registrado pero no tiene grupos, el api regresa **message**, en los casos de que el usuario si tiene grupos el api regresa 
<img width="716" alt="captura de pantalla 2018-12-17 a la s 17 27 20" src="https://user-images.githubusercontent.com/20383899/50122349-ab24c200-0221-11e9-83c3-e337cca13d4b.png">
 **messaage**

**Para reproducir**
Por favor, indícanos qué pasos seguiste cuando apareció la falla, para que nosotros podamos reproducirla:
1. Fui a '...'
2. Dí clic en '....'
3. Bajé a '....'
4. Aparece el error

**Comportamiento esperado**
Coloca una descripción clara y concisa de lo que esperabas que pasara.

**Pantalla**
Si aplica, agrega pantallas para ayudarnos a explicar la falla. 

**Ambiente (por favor completa la siguiente información):**
 - Sistema operativo: [ej. iOS]
 - Dispositivo: [ej. Smartphone, Escritorio]
 - Browser [ej. chrome, safari]
 - Versión [ej. 22]

**Contexto adicional**
Agrega cualquier otro contexto acerca de la falla.

**Comment by aclarturocastro** [comment]
Listo

v1.5.14 ceb4920
