### ISSUE TITLE
Agregar el codigo de curso

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#119]
**La mejora está relacionada a un problema? Por favor describe.**
Para la parte del desglose del pago de las solicitudes de servicio, hace falta agregar el codigo del curso para mostrarlo en el detalle de la solicitud, se debería agregar en el campo details/item para poder obtenerlos con el api 'api/v1/supervisor/request/get?number='

**Describa la solución que propones**
Una descripción clara y concisa de lo que quieres que pase.

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
Se agrega el código de curso a las solicitudes y también los costos.
Los costos también aparecen en la lista de cursos 

v1.6.6 8e68f6d
