### ISSUE TITLE
Modificar el api de cierre de solicitudes

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#133]
**La mejora está relacionada a un problema? Por favor describe.**
Se requiere que el api para el cierre de solicitudes, no borre los datos que se encuentran en los arreglos tmp, esto para que los usuarios puedan consultar el total de alumnos y costos totales por cada solicitud aunque ya se encuentre cerradas, el api es: **api/v1/supervisor/request/finish**

**Describa la solución que propones**
Una descripción clara y concisa de lo que quieres que pase.

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
Listo. API `finish` ya no borra temporales. 

v.1.8.17 bfb7c37
