### ISSUE TITLE
Api para las alertas de comprobante fiscal

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#134]
**La mejora está relacionada a un problema? Por favor describe.**
Se requiere un api para que el usuario pueda subir el comprobante de pago a través de la plataforma y que envíe una notificación ó levante un ticket en la mesa de ayuda para validar el comprobante de pago VS total a pagar de la solicitud. 

**Describa la solución que propones**
Una descripción clara y concisa de lo que quieres que pase.

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
v1.8.18e 401c5c2
