### ISSUE TITLE
Respuestas para el api de intentos

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#2]
me surge una duda en el api de crear el intento, se debe de enviar el arreglo con las respuestas de esta manera:
"answers": [1,0,1,2,0,1,2]
¿de que manera o como el api sabe que respuesta pertenece a cada pregunta? o sea ¿como relaciona esas respuestas con las preguntas del cuestionario?
de este lado yo te podría enviar el indice o posición de la respuesta para que se pueda asociar a la pregunta

**Comment by aclarturocastro** [comment]
Actualmente las preguntas se mandan y tienen que regresar en el orden como fueron enviadas. Tenemos que mejorar este aspecto para tomar en cuenta el id de la pregunta y se regrese la pregunta con el id correspondiente. Así no hay tema. Se propondrá una mejora a este respecto.
