### ISSUE TITLE
Agregar un nuevo tipo de discussion "Tutor"

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#31]
**La mejora está relacionada a un problema? Por favor describe.**
Se requiere un nuevo tipo de discusión para la parte de observaciones del tutor hacia el alumno, actualmente los tipos que se manejan, no contemplan la parte de tutorias

**Describa la solución que propones**
Agregar un nuevo tipo de discusión para poder mostrarla al alumno y que este de su retroalimentación al tutor de sus dudas y comentarios referentes a sus actividades del curso

**Describe alternativas que has considerado**

**Contexto adicional**

**Comment by aclarturocastro** [comment]
Ok... agregaremos el tipo "tutor" para la parte de las discusiones.

**Comment by aclarturocastro** [comment]
Se agregó el tipo "tutor" al pubtype
