### ISSUE TITLE
Cambiar permisos en APIS

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#75]
Se deben cambiar los permisos de las siguientes API para que puedan ser usadas por el supervisor, ya que actualmente se están usando por otros roles dentro del sistema:
/api/v1/orgadm/user/massiveregister <-- Api de creación de usuarios
/api/v1/instructor/group/create <--Api de creación de grupos
/api/v1/instructor/modify <--modificar datos del grupo
/api/v1/instructor/group/createroster <-- Creación de roosters

**Comment by aclarturocastro** [comment]
Gracias. Lo reviso el día de mañana.

**Comment by aclarturocastro** [comment]
v1.4.12 458d079  Se han copiado las rutas para que el supervisor pueda utilizar estos APIs.
