### ISSUE TITLE
Validar el tema del estatus por grupo

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#77]
**La mejora está relacionada a un problema? Por favor describe.**
Para la parte de la vista de los grupos para el supervisor, el api de api/v1/supervisor/group/list debe de regresar el estatus de grupo, el estatus esta en base a si ya esta pagado el grupo o aun esta pendiente de pago

**Describa la solución que propones**
Agregar al JSON que regresa el api un indicar de estatus en base al pago

**Describe alternativas que has considerado**

**Contexto adicional**

**Comment by aclarturocastro** [comment]
Hola. El pago no se define o visualiza en el grupo si no en el roster de cada usuario. Hay una propiedad del roster llamada "status" que define "pending" como pendiente de pago y "active" indicando que ya no hay pendientes de pago. Aunque los pagos se hagan por grupo, el api /api/v1/admin/user/modrs modifica a los usuarios del grupo en masa. Aunque se puede modificar a cada usuario por separado.

**Comment by aclarturocastro** [comment]
El api /api/v1/instructor/group/listroster indica el estatus de cada alumno

**Comment by aclarturocastro** [comment]
Por otro lado, hay que llevar registro de los pagos en la solicitud (que todavía no existe) y relacionarla al (los) grupo(s) que se van a crear. Este trabajo está pendiente todavía

**Comment by aclarturocastro** [comment]
Entonces tiene que ser un registro en cascada... es decir, se registra el pago de la solicitud y esta se "cascadea" al(los) grupos y a su vez al(los) alumno(s) dentro de cada grupo.

**Comment by aclarturocastro** [comment]
Solo habría que considerar los casos que haya pagos seccionados... es decir, que manden pagos por alumno y no por grupo... 
También el caso en que la solicitud es de un solo alumno (una solicitud con un solo grupo con un solo alumno). Digamos que sería el caso para el público en general.

**Comment by aclarturocastro** [comment]
Ejemplo:
[pagos.pdf](https://github.com/ACLSystems/alumno/files/2550435/pagos.pdf)

**Comment by aclarturocastro** [comment]
Hola... qué nos falta en este issue?
