### ISSUE TITLE
API para llevar el control de solicitudes

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#78]
**La mejora está relacionada a un problema? Por favor describe.**
Se requiere un API que lleve el control de solicitudes para los grupos que solicite el supervisor en el panel de grupos

**Describa la solución que propones**
Un API que relacione un número de solicitud para llevar el control de pagos por solicitud de grupos por parte del supervisor

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
Se cierra este caso ya que está repetido con el #33
