### ISSUE TITLE
Agregar el dato del estado por usuario 

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#79]
**La mejora está relacionada a un problema? Por favor describe.**
Para la parte de la creación de nuevo grupos, es necesario contar con el nombre del campus, en este caso es necesario agregar el estado al que pertenece el supervisor para desplegar el listado de campus para que el supervisor pueda seleccionar uno, el api responsable de regresar esta información para su almacenamiento local en la parte del front-end es: _"api/v1/user/getdetails"_

**Describa la solución que propones**
Con el dato del estado por usuario, se puede hacer una consulta de las OrgUnits y así evitar hacer un nuevo API que traiga esa información

**Describe alternativas que has considerado**

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
En este issue agregaremos la funcionalidad de estado y detalles del orgUnit, como name, longName y _id

**Comment by aclarturocastro** [comment]
Lo manda en el api GETROLES

v1.4.18 2219df8
