### ISSUE TITLE
Agregar el código de plantel

### ISSUE THREAD

**Issue by iHectorLeon** [ACLSystems/alumno#81]
**La mejora está relacionada a un problema? Por favor describe.**
Para la parte de creación de grupos, se toma en cuenta el campo NOMBRE DEL PLANTEL que se traduce al número o código con el que es identificado en la zona o estado. Usando el API de "api/orgunit/list?org=" se puede obtener la información de los planteles por estado, qué es lo que se tiene que aplicar para que los supervisores seleccionen el plantel que solicitó el curso, sin embargo en la información que regresa el API no viene este dato. Se adjunta pantalla de como se esta diseñando el QUERY y la repuesta del API, para validar esta información.
<img width="431" alt="captura de pantalla 2018-11-08 a la s 13 46 05" src="https://user-images.githubusercontent.com/20383899/48223441-b5b78600-e35c-11e8-8d5e-16f355d2c2f2.png">

**Describa la solución que propones**
Una descripción clara y concisa de lo que quieres que pase.

**Describe alternativas que has considerado**
Una descripción clara y concisa de las soluciones o funcionalidades alternas que has considerado.

**Contexto adicional**
Cualquier otro contexto o pantallas acerca de la funcionalidad solicitada aquí.

**Comment by aclarturocastro** [comment]
v.1.4.26 721b745

**Comment by aclarturocastro** [comment]
v.1.4.26 4f34fa4
